name: community_managment
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  form_field_validator: ^1.1.0
  glassmorphism_ui: ^0.3.0
  glassmorphism: ^3.0.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/fonts/    
  
  fonts:
    - family: Helvetica
      fonts:
        - asset: assets/fonts/extrabold.ttf
          weight: 900
        - asset: assets/fonts/regular.ttf
          weight: 500
        - asset: assets/fonts/ultralight.ttf
          weight: 200
        - asset: assets/fonts/veryheavy.ttf
          weight: 800
